language: php
php:
  - 5.5
  - 5.6
  - 7.0
services:
  - mysql
  - postgresql
env:
  - DB=mysql
  - DB=postgresql
  - DB=sqlite
install:
  - composer install
  - mv config/config.travis.php config/config.php
before_script:
  - mysql -e 'create database traq_test;'
  - psql -c 'create database traq_test' -U postgres
script: php tests/test.php
matrix:
  allow_failures:
    - env: DB=sqlite
  exclude:
    - php: 5.6
      env: DB=sqlite
    - php: 7.0
      env: DB=sqlite
